use vivek;
/*views*/
create view DIV_STUDENT
as select STANDARD,DIVISION,count(ROLL) AS TOTAL
FROM STUDENT
GROUP BY STANDARD,DIVISION;

SELECT *  FROM DIV_STUDENT
WHERE STANDARD=10;

select * FROM STUDENT;

CREATE VIEW PASSED AS
SELECT ROLL,SNAME,ADDRESS,DOB,STANDARD,DIVISION
FROM STUDENT
WHERE ENGLISH>=35 AND MATHS>=35 AND SCIENCE>=35;

SELECT ADDRESS,count(ROLL) FROM PASSED
GROUP BY ADDRESS;

/*INDEX*/
CREATE INDEX IDX_SNAME ON STUDENT(SNAME ASC);
DROP INDEX IDX_SNAME ON STUDENT ;

select * FROM student 
WHERE SNAME LIKE 'N%';


/*SYNONYM*/
CREATE SYNONYM DS FOR DIV_STUDENT;
