SELECT C.FIRSTNAME,C.LASTNAME,O.ID,OI.UNITPRICE * OI.QUANTITY,P.PRODUCTNAME,S.COMPANYNAME
FROM CUSTOMER C INNER JOIN [ORDER] O
ON C.ID=O.CUSTOMERID
INNER JOIN ORDERITEM OI
ON O.ID=OI.ORDERID
INNER JOIN PRODUCT P
ON P.ID=OI.PRODUCTID
INNER JOIN SUPPLIER S
ON S.ID=P.SUPPLIERID
WHERE C.ID=10;


/*AMOUNT SPENT BY EACH CUSTOMER*/
SELECT CUSTOMER.FIRSTNAME,SUM([ORDER].TOTALAMOUNT) AS AMOUNT
FROM CUSTOMER INNER JOIN [ORDER]
ON CUSTOMER.ID=[ORDER].CUSTOMERID
GROUP BY CUSTOMER.FIRSTNAME;

/*WHAT IS THE SALE OF EACH PRODUCT*/
SELECT PRODUCT.PRODUCTNAME,SUM(ORDERITEM.QUANTITY*ORDERITEM.UNITPRICE)
FROM PRODUCT INNER JOIN ORDERITEM
ON PRODUCT.ID=ORDERITEM.PRODUCTID
GROUP BY PRODUCT.PRODUCTNAME;


/*EHICH SUPPLIER HAS THE MAXIMUM SALES*/
SELECT S.COMPANYNAME,
SUM(OI.UNITPRICE*OI.QUANTITY)
FROM SUPPLIER S INNER JOIN PRODUCT P
ON S.ID=P.SUPPLIERID
INNER JOIN ORDERITEM OI
ON OI.PRODUCTID=P.ID
GROUP BY S.COMPANYNAME
HAVING SUM(OI.UNITPRICE*OI.QUANTITY) = 
(
		SELECT MAX(TOTAL) FROM
		(SELECT S.COMPANYNAME,
	SUM(OI.UNITPRICE*OI.QUANTITY) AS TOTAL
	FROM SUPPLIER S INNER JOIN PRODUCT P
	ON S.ID=P.SUPPLIERID
	INNER JOIN ORDERITEM OI
	ON OI.PRODUCTID=P.ID
	GROUP BY S.COMPANYNAME
			) AS T
);


/*HOW MANY CUSTOMER DOES EACH SUPPLIER SERVE*/
SELECT S.COMPANYNAME,count(distinct(C.ID))
FROM CUSTOMER C INNER JOIN [ORDER] O
ON C.ID=O.CUSTOMERID
INNER JOIN ORDERITEM OI
ON O.ID=OI.ORDERID
INNER JOIN PRODUCT P
ON P.ID=OI.PRODUCTID
INNER JOIN SUPPLIER S
ON S.ID=P.SUPPLIERID
GROUP BY S.COMPANYNAME;