use vivek;
CREATE TABLE SALESDATA
(
	ID INT PRIMARY KEY auto_increment,
	ORDERDATE DATE,
	REGION VARCHAR(4),
	CITY VARCHAR(15),
	CATEGORY VARCHAR(12),
	PRODUCT VARCHAR(20),
	CASES DECIMAL(3),
	CASEPRICE DECIMAL(6,2)
);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-04-30','West','Los Angeles','Cookies','Oatmeal Raisin',288,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-03-10','East','Boston','Cookies','Oatmeal Raisin',193,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-08-15','East','New York','Cookies','Arrowroot',224,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-07-20','East','Boston','Cookies','Chocolate Chip',245,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-29','East','Boston','Cookies','Chocolate Chip',211,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-04-08','East','Boston','Cookies','Oatmeal Raisin',138,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-05-27','East','New York','Cookies','Arrowroot',175,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-02-12','East','Boston','Cookies','Oatmeal Raisin',123,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-23','East','New York','Cookies','Arrowroot',146,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-09-26','West','San Diego','Cookies','Arrowroot',139,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-08-07','East','Boston','Bars','Carrot',144,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-07-27','West','Los Angeles','Bars','Carrot',133,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-01-02','West','San Diego','Bars','Carrot',118,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-06-22','West','Los Angeles','Cookies','Chocolate Chip',107,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-09-27','East','New York','Bars','Carrot',112,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-03-07','East','Boston','Bars','Bran',103,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-08-14','West','Los Angeles','Snacks','Potato Chips',114,40.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-05','East','Boston','Cookies','Arrowroot',87,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-11-01','East','New York','Bars','Carrot',102,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-03-13','West','Los Angeles','Cookies','Oatmeal Raisin',60,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-12-15','West','San Diego','Bars','Bran',86,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-05','West','San Diego','Cookies','Chocolate Chip',82,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-08-20','East','New York','Cookies','Oatmeal Raisin',53,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-17','East','New York','Bars','Carrot',84,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-08-31','West','Los Angeles','Bars','Carrot',82,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-05-24','East','New York','Cookies','Oatmeal Raisin',51,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-10-05','East','Boston','Crackers','Whole Grain',51,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-07-12','East','New York','Bars','Bran',75,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-06-04','East','New York','Bars','Bran',72,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-07-02','West','San Diego','Cookies','Chocolate Chip',70,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-08-29','East','Boston','Crackers','Whole Grain',46,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-04-07','East','New York','Bars','Carrot',71,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-20','West','San Diego','Cookies','Oatmeal Raisin',44,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-09-11','East','Boston','Bars','Bran',66,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-08-03','East','New York','Cookies','Chocolate Chip',65,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-11-30','East','Boston','Bars','Carrot',68,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-12-18','East','New York','Bars','Carrot',67,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-10-06','East','Boston','Crackers','Whole Grain',41,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-27','East','New York','Cookies','Oatmeal Raisin',40,68.16);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-11-05','East','Boston','Cookies','Arrowroot',52,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-02-23','East','Boston','Crackers','Whole Grain',40,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-10-19','East','Boston','Bars','Carrot',63,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-08-12','West','Los Angeles','Cookies','Arrowroot',50,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-04-18','East','New York','Bars','Carrot',61,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-12-27','East','New York','Bars','Bran',57,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-11','East','New York','Bars','Bran',57,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-05-12','East','Boston','Crackers','Whole Grain',38,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-03-14','West','Los Angeles','Bars','Carrot',58,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-04-27','East','Boston','Bars','Carrot',58,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-09-20','East','Boston','Crackers','Whole Grain',36,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-01-21','West','Los Angeles','Bars','Carrot',54,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-06-11','West','San Diego','Bars','Bran',51,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-02-08','East','Boston','Cookies','Arrowroot',43,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-04-29','West','Los Angeles','Bars','Bran',50,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-10-17','East','New York','Cookies','Chocolate Chip',50,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-10-28','East','Boston','Cookies','Chocolate Chip',50,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-05-25','West','San Diego','Bars','Carrot',52,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-11-05','West','Los Angeles','Cookies','Chocolate Chip',47,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-05-11','East','Boston','Cookies','Arrowroot',40,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-06-28','East','New York','Crackers','Whole Grain',30,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-07','East','Boston','Crackers','Whole Grain',30,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-07-22','East','Boston','Crackers','Whole Grain',30,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-12-07','East','Boston','Crackers','Saltines',38,52.56);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-10-04','East','Boston','Cookies','Chocolate Chip',44,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-13','West','Los Angeles','Cookies','Chocolate Chip',43,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-07-16','West','San Diego','Bars','Carrot',45,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-03-21','East','New York','Cookies','Chocolate Chip',40,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-05-05','West','San Diego','Bars','Carrot',42,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-07-19','East','Boston','Cookies','Arrowroot',34,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-03-03','West','San Diego','Cookies','Chocolate Chip',39,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-26','East','New York','Bars','Bran',38,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-01','West','San Diego','Bars','Carrot',40,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-10-18','East','Boston','Cookies','Arrowroot',32,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-10-08','West','Los Angeles','Cookies','Arrowroot',32,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-04-12','East','Boston','Snacks','Pretzels',22,75.6);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-07-04','East','Boston','Cookies','Arrowroot',31,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-11-22','West','Los Angeles','Cookies','Chocolate Chip',36,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-05-16','East','Boston','Snacks','Pretzels',21,75.6);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-03-29','East','Boston','Crackers','Whole Grain',23,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-03-04','East','Boston','Bars','Banana',27,54.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-07-18','East','Boston','Cookies','Arrowroot',28,52.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-04-13','West','Los Angeles','Bars','Carrot',34,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-03-25','East','Boston','Cookies','Chocolate Chip',32,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-04-14','West','Los Angeles','Crackers','Whole Grain',21,66.96);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-11-27','West','San Diego','Bars','Bran',31,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-12-25','West','Los Angeles','Snacks','Potato Chips',33,40.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-05-12','East','Boston','Bars','Carrot',31,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-09-13','East','Boston','Bars','Banana',24,54.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-09-17','West','Los Angeles','Bars','Carrot',30,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-02-21','East','Boston','Bars','Bran',27,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-09-20','West','Los Angeles','Snacks','Potato Chips',29,40.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-10-10','West','Los Angeles','Snacks','Potato Chips',29,40.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-04-12','West','Los Angeles','Bars','Carrot',25,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-04-24','East','Boston','Bars','Carrot',25,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-06-24','East','New York','Bars','Carrot',24,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-02-05','East','New York','Bars','Carrot',23,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-08-22','West','San Diego','Cookies','Chocolate Chip',21,44.88);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-06-26','West','San Diego','Bars','Carrot',20,42.48);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2015-11-23','East','New York','Snacks','Potato Chips',21,40.32);
INSERT INTO SALESDATA(ORDERDATE, REGION, CITY, CATEGORY, PRODUCT, CASES, CASEPRICE) VALUES('2016-05-07','East','New York','Snacks','Potato Chips',20,40.32);

select * from salesdata;

/*Which orders EXCEED THE TOTAL BILL AMOUNT OF ORDER NO. 10*/
SELECT * FROM SALESDATA
WHERE CASES * CASEPRICE >
(
		SELECT CASES * CASEPRICE FROM SALESDATA
        WHERE ID=10
);

/*WHICH ORDER OF CHOCOLATECHIPS IS HIGHER THAN ANY OREDER OF OATMEAL RAISIN*/
SELECT * FROM SALESDATA
WHERE PRODUCT='Chocolate Chip'
AND CASES * CASEPRICE >
(
	SELECT MIN(CASES * CASEPRICE) FROM SALESDATA
    WHERE PRODUCT='Oatmeal Raisin'
);


/* IN WHICH STANDARD MOST STUDENTS HAVE FAILED IN MATHS*/
SELECT STANDARD,count(ROLL) AS FAILED FROM student
WHERE MATHS < 35
GROUP BY STANDARD
HAVING COUNT(ROLL) =
(
	SELECT MAX(FAILED) FROM
    (
		SELECT STANDARD,count(ROLL) AS FAILED FROM student
		WHERE MATHS < 35
		GROUP BY STANDARD
    )AS TEMP
);

/* GRADE STDENTS IN SCIENCE AS PER FOLLOWING
80+ a
65+ B 
50+C 
35+ D 
<35 FAIL
DISPLAY AREPORT CONTAINING STANDARD, GRADE IN SCIENCE AND NO. OF STUDENTS*/

SELECT STANDARD,RESULT,COUNT(RESULT) FROM
(
	select STANDARD,
    CASE WHEN SCIENCE>=80 THEN 'A'
    WHEN SCIENCE BETWEEN 65 AND 79 THEN 'B'
    WHEN SCIENCE BETWEEN 50 AND 64 THEN 'C'
    WHEN SCIENCE BETWEEN 35 AND 49 THEN 'D'
    ELSE 'FAIL' END AS RESULT FROM STUDENT
) AS TEMP
GROUP BY STANDARD, RESULT
ORDER BY STANDARD, RESULT;

/* WHICH STANDARDD HAS THE MOST NO OF STUDENTS WHO HAVE80Y9]O
99DD]/\
'/=/
 SCORED A GRADE*/


SELECT STANDARD,count(ROLL) AS GRADE_A FROM student
WHERE MATHS >=80
GROUP BY STANDARD
HAVING COUNT(ROLL) =
(
	SELECT MAX(GRADE_A) FROM
    (
		SELECT STANDARD,count(ROLL) AS GRADE_A FROM student
		WHERE MATHS >=80
		GROUP BY STANDARD
    )AS TEMP
);
