use vivek;
create table EMPLOYEE
( 
EMP_ID DECIMAL(3,0),
NAME VARCHAR(20),
LASTNAME VARCHAR(20),
MGR_ID DECIMAL(3,0),
ADDRESS VARCHAR(20),
DOB DATE
);

INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(1,'Mahesh', 'Singh',2,'NERUL','1993-2-13');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,ADDRESS,DOB)
VALUES(2,'Aditi','Kumari', 'SEAWOODS','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(3,'Kamal','Sinha',8,'PANVEL','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(4,'Gaurav','Jain',2,'NERUL','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(5,'Arun','Jha',3,'SEAWOODS','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(6,'Pooja','Kamble',2,'PANVEL','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(7,'Mayank','Arora',6,'KHARGHAR','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(8,'Vedika','Nimbalkar',3,'NERUL','1994-2-19');


INSERT INTO EMPLOYEE (EMP_ID,NAME, LASTNAME,MGR_ID,ADDRESS,DOB)
VALUES(9,'Krunal','Patel',6,'PANVEL','1994-2-19');

CREATE TABLE CUSTOMER
(
CID DECIMAL(5,0),
FIRSTNAME VARCHAR(20),
LASTNAME VARCHAR(20),
DOB DATE,
CONSTRAINT CUSTOMER_PK_ID PRIMARY KEY(CID)
);

INSERT INTO CUSTOMER VALUES(1, 'Aditya', 'Mayaramka', '1994-2-19');
INSERT INTO CUSTOMER VALUES(2, 'Suraj', 'Pawar', '1994-2-19');
INSERT INTO CUSTOMER VALUES(3, 'Kamal', 'Yadav', '1994-2-19');
INSERT INTO CUSTOMER VALUES(4, 'Gaurav', 'Sharma', '1994-2-19');
INSERT INTO CUSTOMER VALUES(5, 'Pooja','Kamble', '1994-2-19');
INSERT INTO CUSTOMER VALUES(6, 'Vedika','Nimbalkar', '1994-2-19');
INSERT INTO CUSTOMER VALUES(7, 'Avinash','Kothari', '1994-2-19');
INSERT INTO CUSTOMER VALUES(8, 'Nihar','Palak', '1994-2-19');
INSERT INTO CUSTOMER VALUES(9, 'Nivedita','Sharma', '1994-2-19');
INSERT INTO CUSTOMER VALUES(10, 'Swapnil','Kumar', '1994-2-19');

SELECT * FROM EMPLOYEE;
SELECT * FROM CUSTOMER;

/* HOW MANY CUSTOMRES ARE ALSO IN EMPLOYEE WRITE ONLY THEIR FIRSTNAME*/
SELECT FIRSTNAME FROM CUSTOMER
WHERE FIRSTNAME in
(
	SELECT NAME FROM EMPLOYEE
);

/*HOW MANY CUSTOMERS AND EMPLOYEE DOI HAVE IN TOTAL*/
SELECT FIRSTNAME FROM customer
UNION
SELECT NAME FROM EMPLOYEE;

/*WHICH CUSTOMER ARE NOT MY EMPLOYEE*/
SELECT FIRSTNAME FROM CUSTOMER
WHERE FIRSTNAME NOT in
(
	SELECT NAME FROM EMPLOYEE
);

/*WRITE ONLY THEIR FIRSTNAME AND LASTNAME*/
select FIRSTNAME,LASTNAME FROM customer
WHERE EXISTS
(
	SELECT EMPLOYEE.NAME,EMPLOYEE.LASTNAME FROM
    EMPLOYEE
    WHERE CUSTOMER.FIRSTNAME =EMPLOYEE.NAME
    AND CUSTOMER.LASTNAME = EMPLOYEE.LASTNAME
);

/*which OF MY EMPLOYEE STAY IN PANVEL(ONLY FIRSTNAME)*/
select NAME FROM EMPLOYEE WHERE ADDRESS='PANVEL';


/*which OF MY EMPLOYEE ARE ALSO CUSTOMER STAY IN PANVEL(ONLY FIRSTNAME)*/
SELECT NAME FROM EMPLOYEE
WHERE ADDRESS='PANVEL' AND NAME in
(
	SELECT FIRSTNAME FROM CUSTOMER
);

/*HOW MANY EMPLOYEE ARE ALSO MY CUSTOMER*/
SELECT COUNT(NAME) FROM EMPLOYEE
WHERE NAME in
(
	SELECT FIRSTNAME FROM CUSTOMER
);

/*COUNT THE NO. OF EMPLOYEE(WHO R NOT MY CUSTOMER) BY ADDRESS*/
SELECT COUNT(NAME),ADDRESS FROM EMPLOYEE
WHERE NAME NOT in
(
	SELECT FIRSTNAME FROM CUSTOMER
)
GROUP BY ADDRESS;