create database facebook;
use facebook;

CREATE TABLE F_USER
(
USERID INT PRIMARY KEY NOT NULL,
USERNAME VARCHAR(20),
GENDER varchar(10),
EMAIL VARCHAR(25),
MOBILE_NO VARCHAR(10),
ADDRESS VARCHAR(20),
DOB DATE
);